version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456789q
      MYSQL_DATABASE: inspiration
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456789q
    ports:
      - "9906:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
